Install BashX test

diff --git a/bxrun b/bxrun
--- a/bxrun
+++ b/bxrun
@@ -22,7 +22,7 @@ export BASHX_DIR="$BASE_DIR"
 cd "$BASE_DIR"
 if [ ! -d "${BASHX_DIR}" ]; then
   echo "Installing BashX..."
-  git clone git@github.com:reduardo7/bashx.git "${BASHX_DIR}"
+  git clone git@github.com:reduardo7/bashx.git "${BASHX_DIR}" || echo "Error installing BashX" && exit 1
 fi
 . "${BASHX_DIR}/src/bashx.sh"
 run "$@"
